name: publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    env:
      PROJECT_ID: extframework
      REGION: us-central1
      GAR_URL: us-central1-docker.pkg.dev/extframework/docker-images
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Google Auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"
      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      - name: Build image
        run: docker build ./ --tag ${{ env.GAR_LOCATION }}:latest
      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}:latest
